name: "Docker: whmserver PR build"

on:
  pull_request:
    # trigger when commits are pushed to a PR
    types: ["synchronize"]
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: WormholeMapper/whmserver

jobs:
  build-whmserver-container:

    permissions:
      contents: read
      packages: write

    runs-on: [self-hosted, linux]

    steps:
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Gather Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/WormholeMapper/whmserver
          tags: |
            type=ref,event=pr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}


